** Cocotte de verduras y pollo al pimentón
*** Información
- Comensales: 4 personas
- Fuente: http://www.gastroandalusi.com/2014/09/cocotte-de-verduras-y-pollo-al-pimenton.html
*** Ingredientes
- 2 patatas grandes
- 4 zanahorias
- 1 cebolla grande
- 2 limones
- Tomillo
- 2 pechugas de pollo
- Pimentón de la vera dulce
- 1/2 litro de caldo de pollo
- Pimienta negra
- Sal
- Aceite de oliva virgen extra
*** Preparación
1. Pelamos las zanahorias, la cebolla y las patatas.
2. En una cocotte (fuente especial para horno), cubrimos la base con aceite de
   oliva virgen extra y ponemos las patatas troceadas, las zanahorias partidas
   en dos mitades, y la cebolla en gajos. Por encima de las verduras, ponemos
   las rodajas de un limón y ramitas de tomillo. Metemos en el horno previamente
   precalentado durante 35 minutos a 180º.
3. Mientras, salpimentamos las pechugas con pimienta negra, sal y pimentón dulce
   y en una plancha o sartén pincelada con aceite de oliva virgen extra, pasamos
   las pechugas vuelta y vuelta (para que queden selladas pero no hechas del
   todo).
4. Sacamos la cocotte o la fuente del horno, y le añadimos el caldo de pollo. Le
   ponemos las pechugas por encima y volvemos a meter en el horno unos 15
   minutos aproximadamente hasta que las patatas estén en su punto. 
