** Charlota de tortilla rellena
*** Información
- Comensales: 4 o 6 personas
- Fuente: http://webosfritos.es/2010/06/charlota-de-tortilla-rellena/
*** Ingredientes
- 4 patatas hermosas
- 4 huevos grandes y frescos
- Un poco de sal
- Aceite de oliva
- Unas lonchas de un buen jamón de York o de lacón cocido
- Una lata de bonito del norte en escabeche
- Unas aceitunas rellenas de anchoa
- 3 cucharas soperas de mayonesa casera
- 2 tomates hermosos de buen sabor
- 1 cogollo de lechuga
*** Ingredientes para la tortilla que cubre la tarta
- 2 huevos
- Un poco de sal
- Unas gotas de aceite
*** Preparación
1. Pelar las patatas, lavarlas y secarlas. Cortarlas en pequeñas
   láminas. Freírlas en abundante aceite de oliva, a fuego medio. Lo
   ideal es que se queden hechas, pero ni tostadas ni
   tiesas. Escurrirlas del aceite sobrante y sacarlas a un bol, en el
   que ya tendremos batidos los cuatro huevos con un poco de sal.
2. Cuajar la tortilla en una sartén antiadherente. Si la sartén es
   buena, con muy poco aceite será suficiente. La tortilla tiene que
   quedar jugosa, pero ni dura, ni con huevo sin cuajar. Aquí ganará
   el gusto de cada casa, pero como es para un pastel, preferiblemente
   muy cuajada. Dejar templar.
3. Trasladar la tortilla al plato de presentación. Poner encima una
   capa de lonchas de jamón de york.
4. Poner en un bol la mayonesa, el bonito escurrido, desmenuzado, y
   las aceitunas troceadas. Remover hasta conseguir una pasta.
5. Poner esta mezcla encima del jamón de York. Sobre ella, los tomates
   en rodajas, con una pizca de sal, y la lechuga, que habremos lavado
   y secado con sumo cuidado —mejor hojas enteras que troceadas,
   porque así, al partir, queda el corte perfecto.
6. Batir dos huevos, y ponerles una pizca de sal. En una sartén
   antiadherente, un poco más grande que la que hemos usado para la
   tortilla de patata, hacer una tortilla tipo crêpe, es decir,
   dejando que cuaje por un lado para luego darle la vuelta con un
   plato para que quede un círculo perfecto.
7. Cubrir con esta tortilla el resto de la tarta.
8. Poner un poco de mayonesa en los laterales y forrarla con los
   panecillos tostados que os gusten, consiguiendo así nuestra
   charlota tan particular. Adornar con un lazo y cualquier detalle
   que os guste e inspire.
** Huevos rellenos de aguacate
*** Información
- Comensales: 6 personas
- Fuente: http://webosfritos.es/2012/08/huevos-rellenos-de-aguacate/
*** Ingredientes para 6 personas
- 12 huevos
- 1 aguacate
- 1 tomate de buen sabor
- 1 lata de anchoas en aceite de buena calidad
- 4 cucharadas soperas de mayonesa
*** Preparación
1. Cocer los huevos durante 10 minutos contando desde que el agua
   empiece a hervir. Refrescarlos en agua fría.
2. Mientras tanto, pelar un tomate, y cortarlo en dados muy
   pequeños. Ponerlo a escurrir en un colador.
3. Escurrir las anchoas y partirlas en trozos pequeños.
4. Pelar el aguacate, quitarle el hueso, y cortarlo también en trozos
   pequeños.
5. Pelar los huevos. Cortar un extremo de cada huevo y sacar con
   cuidado la yema procurando no romper la clara. Yo me ayudo de un
   sacabocados y de un cuchillo pequeño de punta fina. Quitar incluso
   un poco de clara por dentro, pero sin romper el huevo, de manera
   que quepa más relleno. Cortar una yema cocida en trocitos.
6. Una vez que el tomate esté bien escurrido —este tema es
   fundamental, porque si no, nos arruina los huevos rellenos—
   mezclar en un recipiente todos los ingredientes con la mayonesa.
7. Rellenar suficientemente los huevos. Rallar por encima otra yema
   de huevo, con un rallador de agujero pequeño. Depositarlos en una
   bandeja o un recipiente como el que veis en la foto. Para usar la
   bandeja hay que cortar una pizca el otro extremo del huevo para
   que asiente bien.
8. Si los ingredientes están fríos, servir inmediatamente. Si no los
   vas a consumir de inmediato, ponlos en el frigo tapados con un
   plástico sin la yema rallada, que pondrás justo antes de servir.
** Nubes de huevo
*** Información
- Comensales: 4 personas
- Fuente: http://cavemanketo.com/eggs-in-a-cloud/
*** Ingredientes
- 4 huevos grandes
- 200 gramos de bacon troceado
- Sal
- Pimienta
- Cebolla en polvo
- Ajo en polvo
- 2 cucharadas de queso parmesano
*** Preparación
1. Separarar las yemas de las claras.
2. Cortar el bacon en taquitos y cocinarlo en una sartén hasta que esté
   crujiente. No hace falta añadir aceite.
3. Poner las claras de los huevos en un bol y montarlas.
4. Rallar el queso parmesano en la claras montadas y añadir el bacon también.
5. Formar las nubes con un hueco en el centro encima de una bandeja con papel
   de horno.
6. Cocinar las claras a 180º unos 5 minutos.
7. Colocar cada yema de huevo en el hueco de cada nube.
8. Cocinar hasta que las claras estén tostadas.
** Pasta de huevo
*** Ingredientes
- Huevos
- Sal
- Pimienta
- Aceite de oliva
*** Preparación
1. Cocer los huevos.
2. Trocearlos y ponerlos en un bol.
3. Echarle sal, pimienta y aceite de oliva al gusto.
4. Triturar un poco.
*** Notas
- Se suele tomar en tostadas, como si fuera mantequilla, para desayunar.
** Pastel de tortillas
*** Información
- Comensales: 6 personas
- Fuente: http://webosfritos.es/2010/01/pastel-de-tortillas/
*** Ingredientes para la tortilla de espinacas
- 600 gramos de espinacas frescas
- Sal
- 3 huevos
- Una cucharada de aceite de oliva virgen extra
- Medio diente de ajo
*** Ingredientes para la tortilla de bonito
- 200 gramos de bonito del Norte en escabeche
- 3 huevos
- Una cucharada de aceite de oliva virgen extra
*** Ingredientes para la tortilla de gambas
- Medio kilo de gamba roja
- 3 huevos
- Sal
- Pimienta blanca molida
- Una cucharada de aceite de oliva virgen extra
*** Resto de ingredientes
- 1 huevo más
- 250 mililitros de leche
- Una cucharada sopera colmada de harina
- Tres cucharadas de aceite de oliva virgen extra
- Un poco de sal
- Un poco de nuez moscada
- Queso manchego curado rallado al gusto
*** Preparación
1. Cocer las espinacas en una cacerola con un poco de agua caliente y sal
   durante unos 4 minutos. Escurrir y sofreir con medio diente de ajo. Ponerlas
   a fuego medio-bajo y con una tapa. Batir 3 huevos, comprobar el punto de sal
   de las espinacas y echarlas en el huevo, removerlas y verter todo en la
   sartén con una cucharada de aceite. Cuando esté bien caliente, echar y hacer
   la tortilla, primero a fuego medio-fuerte y luego bajar un poco el fuego
   para que se cuaje bien por dentro. Reservar.
2. Abrir la lata de bonito y escurrirla. Batir los huevos y echar el bonito en
   ellos, desmigándolo. Poner en la sartén una cucharada de aceite de oliva y
   cuando esté caliente, hacer la tortilla, teniendo especial cuidado de que se
   haga por dentro. Reservar.
3. Pelar las gambas y salpimentarlas. Batir 3 huevos en un bol. Poner en la
   sartén un poco de aceite y cuando esté caliente, echar las gambas y freirlas
   unos segundos. Echarlas en el bol de los huevos batidos. Limpiar la sartén
   con un papel de cocina, y echar nuevamente unas gotas de aceite y cuajar la
   tortilla, que quede hecha pero no demasiado seca.
4. Dejar templar las tres tortillas un poco.
5. Con un cortapastas o un aro de emplatar y un cuchillo afilado marcar los
   centros de las tortillas, presionar el aro y, con la cuidadosa ayuda de la
   otra mano por debajo de la tortilla, la parte central sale fenomenal.
   Intercambiar los centros al gusto.
6. Batir un huevo hermoso más. Poner la sartén y echar la primera tortilla y en
   la zona del centro, echar un poco de huevo para que cuaje. No tenerla mucho
   tiempo: sólo lo justo para que el centro se una. Hacer lo mismo para las
   otras dos tortillas. Reservar.
7. Preparar una bechamel: en un cazo poner el aceite y cuando esté caliente,
   añadir la harina, dejar que se tueste, y, a continuación, echar poco a poco
   la leche, la sal y un poco de nuez moscada rallada y con unas varillas
   integrar todo hasta que espese.
8. Poner el horno a calentar para gratinar. Montar las tortillas unas encima de
   otras, poner la bechamel por encima, rallar un poco de queso manchego curado
   sobre ella, y meter en el horno a gratinar.
** Tamagoyaki
*** Información
- Tortilla japonesa
- Fuente: http://eugeniekitchen.com/korean-egg-rolls/
*** Ingredientes
- 3 huevos
- 1 cucharada de leche
- 1 cucharada de zanahoria muy picada
- 1 cucharada de cebolla muy picada
- 1 cucharada de cebolleta muy picada
- Media cucharadita de sal
- Pimienta
*** Preparación
1. Cascar los huevos en un bol y agregar la leche y la sal. Batir hasta que se
   mezclen. Pasar por un colador fino para eliminar la chalaza. La chalaza
   contiene colesterol y se elimina para que la textura del plato sea más fina.
2. Añadir la zanahoria, la cebolla, la cebolleta y la pimienta y remover hasta
   que se mezclen.
3. Engrasar ligeramente una sartén con aceite vegetal y calentar la sartén. A
   continuación, verter la mitad de la mezcla de huevo y cocinar a fuego lento
   hasta que a medio hacer.
4. Enrollar la tortilla hasta la mitad. Si no hay suficiente aceite, engrasar
   ligeramente la sartén cada vez que se enrolle. Añadir la mitad de la mezcla de
   huevo restante a un lado de la tortilla. Cocinar hasta que a medio hacer.
5. Enrollar de nuevo hasta la mitad y mover el rollo de huevo hasta el centro de
   la sartén. Agregue la mezcla de huevo restante y cocinar hasta que esté hecho.
6. Terminar de enrollar el resto de la tortilla.
7. Mover el rollito a una table de cortar. Cuando un rollo de tortilla está
   caliente se rompe con facilidad, por lo que hay que dejar enfriar antes de
   cortar.
8. Cortar en trozos pequeños.
** Tortilla de patatas gratinada
*** Ingredientes para 4 personas
- 3 patatas grandes
- Sal
- Aceite de oliva virgen extra
- 4 huevos grandes
- 250 gramos de carne picada
- 5 cucharadas de tomate frito casero
- 100 gramos de queso tipo mozarella o para fundir
*** Preparación
1. Poner un poco de aceite de oliva en una sartén, sofreír la carne picada con
   un poco de sal, y retirarla a un plato.
2. Pelar las patatas, lavarlas y secarlas. Cortarlas en pequeñas láminas.
   Freírlas en abundante aceite de oliva virgen extra, a fuego medio. Lo ideal
   es que queden hechas, pero ni tostadas, ni tiesas.
3. Batir los cuatro huevos con un poco de sal en un cuenco.
4. Sacar las patatas, escurrirles el aceite sobrante, y sacarlas al cuenco con
   los huevos batidos.
5. Añadir la carne picada.
6. Cuajar la tortilla en una sartén antiadherente. Si la sartén es buena, con
   muy poco aceite será suficiente. La tortilla tiene que quedar jugosa, pero
   ni dura, ni con huevo sin cuajar. Aquí ganará el gusto de cada casa, pero 
   como es para gratinar, preferiblemente al punto, no muy hecha. Dejar templar.
7. Poner el tomate frito extendido por encima de la tortilla, y sobre este,
   queso rallado.
8. Encender el horno con la función gratinador, y gratinar la tortilla justo 
   antes de servir.

** Tortilla de verduras
*** Información
- Comensales: 2 o 4 personas
- Fuente: http://www.recetasdemama.es/2013/08/tortilla-de-verduras/
*** Ingredientes
- 4 huevos
- 1 patata mediana
- 1 cebolla grande
- 1 calabacín
- 1 pimiento rojo
- 2 pimientos verdes
- Aceite de oliva virgen extra
- Sal
*** Preparación
1. Se pelan y se lava la patata y se corta en laminas finas. Se pone a calentar
   una sartén con aceite de oliva y se van añadiendo la patata, la cebolla
   cortada en juliana, los pimientos cortados a tiras y un poco de sal. El fuego
   no debe estar demasiado fuerte, para que las verduras queden bien en su
   punto. Cuando están a media cocción, se añade el calabacín cortado en
   daditos.
2. Cuando empiezan a dorarse las verduras, se retira todo del fuego, y se pone
   todo en un colador grande para que escurra el aceite sobrante. Mientras
   tanto se baten los huevos y se añaden las patatas y verduras, se mezcla todo
   bien y se rectifica de sal.
3. Se prepara de nuevo la sartén en el fuego con dos cucharadas de aceite que
   cubran bien el fondo de la sartén. Se echa la mezcla del huevo y verduras y
   se baja el fuego. Se mueve con movimientos circulares para que la tortilla se
   mueva y no se pegue al fondo de la sartén.
4. Cuando empieza a hacer burbujas es que está cuajada, y es el momento de dar
   la vuelta. Yo utilizo un plato llano, pero se puede usar una tapadera de
   borde liso. Si se ve que hace falta, se pone otro poquito de aceite en la
   sartén antes de dejar resbalar suavemente la tortilla desde el plato a la
   sartén, y se mueve de nuevo con movimientos circulares.
** Tortilla guisada
*** Información
- Comensales: 4 personas
- Fuente: http://webosfritos.es/2008/02/tortilla-guisada/
*** Ingredientes
- 5 patatas hermosas
- 5 huevos
- Sal
- Aceite de oliva virgen extra
- Media cebolla
- 1 trozo de puerro
- Una cucharadita de pimentón dulce
- Unos granitos de pimienta
- Una cucharada de harina
- Un vaso de agua
- Una hoja de laurel
*** Preparación
1. Pelar la patata, lavarla, secarla con un papel de cocina y
   cortarla en lonchas finas.
2. Poner aceite abundante en una sartén y cuando esté caliente,
   añadir la patata con la sal.
3. Dejar freír, hasta que estén hechas, pero de con cuidado de que no
   se quemen.
4. En un bol batir los 5 huevos muy bien, con un poco de sal, para
   que la tortilla quede muy esponjosa.
5. Sacar con una espumadera las patatas de la sartén escurriéndolas
   para que no tengan exceso de aceite y echarlas en el bol.
6. Mover la patata con un tenedor, para que coja el huevo por igual.
7. En una sartén no demasiado ancha —esta receta requiere una
   tortilla gorda— poner un chorrito de aceite del que nos ha sobrado
   de freír las patatas.
8. Cuando esté caliente echar las patatas con el huevo. Con una
   espumadera ir dando forma a la tortilla para que quede bien
   redondita.
9. Darle la vuelta ayudándonos de un plato y cuajar por el otro
   lado. Repasar los bordes con la espumadera y darle la vuelta
   nuevamente.
10. La volcamos en una cacerola, a la que añadimos unos granos de
    pimienta y el laurel.
11. Para preparar la salsa, en una sartén poner un poco de aceite del
    que hemos utilizado para freír las patatas, y pochar la cebolla y
    el puerro. Cuando estén listos, añadir una cucharada de harina y
    un poco de pimentón dulce. Echar en la propia sartén del sofrito
    el agua y dejar que se ligue un poco la salsa.
12. Echar la salsa por encima de la tortilla. Ponerla a fuego medio y
    dejar cocer de 5 a 10 minutos, para que los sabores se fundan.
