** Crepes
*** Información
- Cantidad: 4 crepes de unos 28 centímetros de diámetro
- Fuente: http://javirecetas.hola.com/crepes-receta-de-crepes/
*** Ingredientes
- 125 gramos de harina de trigo
- 250 mililitros de leche entera
- 2 huevos grandes
- 25 gramos de mantequilla sin sal
- 1 pizca de sal
- Un poco de mantequilla para cocinar los crepes
- (Para crepes dulces) 1 cucharada de azúcar
- (Para crepes salados) Otra pizca de sal y algunas hierbas frescas picadas
*** Preparación
1. Pon un colador grande sobre un cuenco y añade 125 gramos de harina. Tamiza la
   harina sobre el cuenco.
2. Haz un pequeño hueco en el centro de la harina y añade dos huevos grandes.
   Mezcla un poco con un batidor de varillas y luego echa 25 gramos de
   mantequilla derretida y una pizca de sal. Mezcla otro poco.
3. Ahora vamos incorporando 1/4 de litro de leche poco a poco mientras batimos
   hasta que quede una mezcla homogénea. Para asegurarnos de que no queden
   grumos pon un colador sobre una jarra y pasa la mezcla por un colador.
4. En este momento ya tenemos preparada una masa de crepes que nos servirá tanto
   para hacer crepes dulces como crepes salados. Si vamos a utilizar la masa
   para hacer crepes salados puedes añadir una pizca más de sal y alguna hierba
   fresca picada para darle sabor y color (por ejemplo una cucharada de perejil
   picado). Si vas utilizar la masa para hacer crepes dulces añade 1 cucharada
   de azúcar y mezcla bien.
5. Luego tapa la jarra con la masa de crepes y deja reposar durante al menos
   media hora (si va a reposar más tiempo métela en el frigorífico).
6. Pasado este tiempo mezcla un poco con un tenedor. Pon una sartén de 26 o 28
   centímetros de diámetro al fuego y añade un trocito de mantequilla. Cuando se
   derrita la mantequilla echamos un poco de la masa de crepes en la sartén y la
   giramos para que se extienda por todo el fondo. Dejamos que se dore durante
   un minuto y luego le damos la vuelta con una espátula. Dejamos unos segundos
   más hasta que se dore y sacamos a un plato.
7. Repite con el resto de la masa hasta que se termine y solo nos quedará
   rellenar las crepes a nuestro gusto.
** Hojaldre
*** Ingredientes
- 500 gramos de harina de fuerza
- 250 gramos de agua a temperatura ambiente
- 60 gramos de mantequilla fundida
- 12 gramos de sal
- 350 gramos mantequilla en bloque
*** Preparación
1. Hacer un plastón (así es como se le llama a la masa cuando vamos a hacer
   hojaldre): poner la harina en la mesa de trabajo. Hacer un hueco en el
   centro. Meter en el hueco el agua, la sal y la mantequilla fundida.
   Incorporar hacia dentro la harina poco a poco hasta formar una bola. No
   trabajar demasiado.
2. Marcar una cruz profunda con un cuchillo.
3. Meter al frigorífico de media hora a dos horas.
4. Sacar la masa de la nevera y extenderla con el rodillo en forma de cruz,
   dejando un poco más de masa en el centro.
5. Utilizar una mantequilla en bloque y si es necesario le daremos unos cuantos
   golpes para conseguir que quede con forma de prisma rectangular bajo. Para
   ello hay que sacarla veinte minutos antes del frigorífico.
6. A continuación, envolver la mantequilla con los brazos de la cruz, como si de
   un paquete se tratase.
7. Retirar el exceso de harina con una brocha.
8. Golpear el paquete repetidamente, dando unos toques con el rodillo.
9. En cuanto se pueda, empezar a extenderlo con el rodillo en una sola
   dirección, hasta conseguir un rectángulo.
10. Doblar en tres partes. Primero la más alejada de nosotros y luego la más
    cercana.
11. Lo giramos 90º y volvemos a estirar y doblarlo en 3 partes. Con ello se
    completan dos vueltas.
12. Meter el cuadrado en la nevera 20 minutos.
13. Volvemos a estirarlo y doblarlo otras dos veces. Con ello se completan 
    cuatro vueltas.
14. Meter el cuadrado en la nevera 20 minutos.
13. Volvemos a estirarlo y doblarlo otras dos veces. Con ello se completan
    seis vueltas.
** Hojaldre rápido
*** Ingredientes
- 200 gramos de mantequilla congelada en trozos pequeños
- 200 gramos de harina
- 90 gramos de agua helada (o 40 de agua y 50 vino blanco muy frío)
- 5 gramos de sal
*** Preparación tradicional
1. Poner la harina y la sal en un cuenco, y echar los trozos de mantequilla
   congelada por encima. Echar el agua —o el agua y el vino— y mezclar con una
   espátula o una rasqueta.
2. Hacer una bola aplanada sin manosear mucho la masa. Realizar unos cortes en
   forma de rejilla en la superficie. Envolver en plástico transparente y meter
   en el frigorífico 1 hora.
3. Sacar del frigorífico, quitar el plástico y poner la masa encima de la
   encimera espolvoreada con un poco de harina.
4. Estirar con el rodillo hasta formar un rectángulo de 1 cm de espesor.
5. Doblar en tres partes. Doblamos la parte de abajo hacia arriba y la de arriba
   hacia abajo.
6. Lo giramos 90° en el sentido de las agujas del reloj.
7.  Repetir el proceso extendiendo otra vez la masa hasta formar un rectángulo y
    haciendo los dobleces. Es nuestra segunda vuelta.
8. Meter en el frigorífico envuelta en plástico transparente durante media hora.
   Repetir una vez más el proceso, para completar la tercera y la cuarta vuelta.
   Meter en el frigorífico de nuevo de veinte minutos a media hora.
9. Repetir el proceso las 2 últimas veces para conseguir la quinta y la sexta
   vuelta. Sólo queda meterla de nuevo en el frigorífico 1 hora para que esté
   lista para usar.
** Masa de pizza
*** Ingredientes
- 1 kilo de harina de trigo de fuerza
- Medio litro de agua templada
- 25 gramos de sal (a partir de esta medida, si te gusta un poco más salada,
  incrementa la medida)
- 50 mililitros de aceite de oliva virgen extra
- 25 gramos de levadura fresca de panadero o 8 g de levadura liofilizada de panadero
*** Preparación
1. En un bol grande introducimos parte de la harina de trigo. Dejamos unas 4 
   cucharadas de harina separadas para ir engordando la masa.
2. Con una cuchara hacemos un hoyo en el centro del bol y echamos la levadura
   disuelta en el agua.
3. Batimos con una cuchara de madera desde el centro hacia afuera y vamos poco
   a poco mezclando con la harina.
4. Añadimos el aceite de oliva virgen extra y la sal (es importante que la sal
   y la levadura no entren en contacto directo para no tener problemas en el 
   proceso de fermentación). Seguimos removiendo lo que empieza a ser la masa,
   por ahora será una mezcla pegajosa pero firme.
5. Preparamos la zona donde vamos a amasar. Llenamos la zona de la encimera de
   harina, sacamos la masa del bol y empezamos a trabajar la masa con las 
   manos. Es muy importante el refinado de la masa para que quede más elástica
   y suba mejor. Para refinarla estirar la masa como un churro y retorcerla en
   espiral varias veces. Al final volvemos a juntar y amasar de nuevo durante 
   unos diez minutos. Este es el truco que hace que la masa sea increíble.
6. Después de esos 10 minutos, podremos manipular la masa con más rapidez, se 
   irá quedando elástica y homógenea. La medida de harina correcta es hasta que
   la harina no se pegue a las manos, pero tampoco se debe de abusar.
7. Vamos tornando la masa en una bola. Cogemos el anterior bol y lo 
   enharinamos. Introducimos la bola de masa en él. Tapamos el bol con un trapo
   de algodón de unos 45 minutos a 1 hora. Para saber el tiempo que se debe
   dejar levar la masa, utiliza el siguiente truco: si la apretamos con un dedo
   y la masa vuelve a su posición original estará lista para preparar.
*** Notas
- Forma de decoración alternativa: http://i.imgur.com/l8f4zed.jpg
** Masa de wonton
*** Ingredientes
- 1 huevo
- 150 gramos de harina
- Agua
- Sal
*** Preparación
1. Colomos sobre la mesa la harina, a la que añadiremos un huevo y agua.
2. Trabajar amasándola con cuidado. Añadir la sal uniformemente.
3. Cuando esté lista dejarla reposar.
4. Cortar en pequeños cuadrados que usaremos fritos o hervidos.

** Pasta choux
*** Ingredientes
- 130 gramos de agua
- 120 gramos de leche
- 100 gramos de mantequilla
- 1 pellizco de sal
- 5 gramos de azúcar
- 160 gramos de harina de repostería
- 4 huevos medianos
*** Preparación tradicional
1. Precalentar el horno a 180°.
2. Pesar la harina, tamizar y reservar.
3. Poner en un cazo antiadherente la leche, el agua, la mantequilla,
   la sal y el azúcar. Remover con unas varillas a fuego medio hasta
   que esté todo bien integrado.
4. Cuando rompa a hervir, retirar del fuego y añadir la harina de
   golpe. Remover con unas varillas –mejor electricas-y ponerlo a
   fuego medio para que cueza un poco, lo justo para que se integre
   bien. Cuando asoma la grasa de la mantequilla, está listo.
5. Retirar del fuego y añadir uno a uno los huevos, removiendo
   constantemente con las varillas. No añadir el siguiente hasta que
   no esté bien integrado.
6. Verter la pasta en una manga pastelera de boquilla rizada grande.
7. Sobre papel de hornear disponer porciones separadas unas de otras,
   y hornear unos 30 minutos.
8. Sacar a una rejilla cuando estén horneados.

** Tempura
*** Ingredientes
- 2 yemas de huevo
- Agua (puede ser agua con gas o cerveza)
- Harina (tamizada, puede ser harina normal y maicena a partes iguales)
- Licor de arroz (opcional)
*** Preparación
1. Se rompen las yemas de huevocon unos palillos, y se vierten en un vaso de
   agua casi helada. De esta manera, se formará una crema poco uniforme.
2. Se agrega la misma medida de harina que de agua y un toque de licor de arroz,
   si se cuenta con él. Se mezcla todo, pero sin remover mucho.
3. En cuanto tenga cierta consistencias se pone a punto de sal (también se puede
   utilizar ralladura de limón o un poco de ajo y perejil picado).
*** Notas
- El hecho de que no sea necesario remover en exceso tiene una explicación:
  evitar que la masa coja "liga", es decir, quede elástica. Si se utiliza una
  masa así para rebozar un alimento, al freírla encogerá y dejará zonas sin
  cobertura. Sin remover demasiado, se obtendrá una masa con pequeños grumos (no
  importa).
- Lo importante en este punto es prever con qué salsa se acompañará la tempura
  en la mesa. Si se utiliza una salsa de soja, que es muy salada, no se pondrá
  sal a la tempura para evitar excesos.
