** Callos
*** Ingredientes
- 1 kilogramos de callos frescos
- 1 kilogramos de garbanzos
- Un chorizo
- Un trozo de jamón serrano
- Una cebolla grande
- Una cabeza de ajos
- 3 o 4 dientes de ajo pelados
- Pimentón molido dulce
- Sal
- 200 mililitros de aceite de oliva
- Un manojo de hierbabuena
- Medio bote de especias para menudo en grano
- Vinagre
*** Preparación
1. La noche anterior ponemos en remojo los garbanzos. Como mínimo deben estar 
   12 horas en remojo.
2. Lavar muy bien los callos: cortar los callos a trocitos y limpiarlos muy bien
   con sal y vinagre. Enjuagamos y volvemos a limpiar varias veces hasta que el
   agua quede clara y no huela a vinagre.
3. En la olla a presión metemos los callos cubriéndolos de agua, metemos la
   cebolla zanjada y la cabeza de ajo (sin pelar) y sal al gusto. Cerramos la
   olla y una vez que pite contamos 30 minutos. Mientras tanto, cortamos el
   chorizo por la mitad y luego a rodajitas y el jamón a taquitos. 
4. A continuación, agregamos a la olla los garbanzos, el aceite, el chorizo, el
   jamón, el pimentón molido (hasta que el caldo se vea rojizo) y unas hojas de
   hierbabuena. Por otro lado, batimos las hojas de hierbabuena que nos han
   sobrado junto con los dientes de ajo pelados y un pellizco de sal junto con
   un poco del caldo de los callos. Añadimos a la olla.
5. Añadimos un puñado de especias a la olla metidas en una gasa o bolsita.
   Cerramos de nuevo la olla a presión y dejamos al fuego otros 40 minutos.

** Fabes con almejas
*** Información
- Fuente: Escuela MasterChef
*** Ingredientes
- 500 gramos de fabes 
- 2 cebollas
- 1 puerro
- 1 pimiento verde
- Un kilogramo y medio de almejas de buen tamaño
- 500 gramos de huesos de rape
- 1 vaso de vino blanco
- Perejil
- Aceite de oliva virgen extra
*** Preparación
1. Hacemos un caldo con los huesos de rape y reservamos.
2. Ponemos a cocer las fabes, previamente remojadas, en el caldo frío
   con una cebolla entera partida por la mitad. Las cocemos durante
   unos 80 minutos aproximadamente, hasta que las fabes estén tiernas.
3. Paralelamente, hacemos un buen sofrito con dos ajos, una cebolla y
   un pimiento verde picado en brunoise, y añadimos el vaso de
   vino. Dejamos reducir. Añadimos el conjunto a las verdinas
   cociéndose.
4. Si cuando se ha terminado de cocer la verdina el guiso no tiene el
   espesor deseado, trituramos unas cuantas fabes con un poco de caldo
   para darle la consistencia deseada.
5. Mientras se está cociendo el guiso, abrimos las almejas con un poco
   de caldo del guiso. El caldo obtenido se añadirá al guiso. Las
   almejas las limpiamos y las reservamos.
6. Una vez cocidas las fabes, servimos añadiendo las almejas y un poco
   de perejil picado.
** Garbanzos con arroz
*** Información
- Comensales: 6 personas
- Fuente:
  http://www.hogarutil.com/cocina/recetas/legumbres/201109/garbanzos-arroz-10740.html
*** Ingredientes
- 300 gramos de garbanzos 
- 200 gramos de arroz 
- 1 morcilla
- 1 huevo cocido
- 2 puerros
- 1 cebolla
- 2 dientes de ajo 
- Una pizca de pimentón 
- Agua
- Aceite virgen extra
- Sal
- Perejil
*** Preparación
1. En la víspera, pon a remojo los garbanzos. Cuece la morcilla a
   fuego suave, en una cazuela con una pizca de sal y unas ramas de
   perejil. Pon agua a cocer en la olla rápida, cuando esté hirviendo,
   agrega los garbanzos y una pizca de sal. Tápala y deja cocer
   durante 15 o 20 minutos desde que empiece salir el vapor.
2. Pasados los 20 minutos, agrega el arroz.
3. Pica finamente la cebolla, los puerros y los dientes de ajo. Pon a
   pochar en una sartén con un poco de aceite.
4. Cuando la verdura esté dorada, agrega el pimentón, mezcla bien y
   añádela a la olla. Deja cocer todo junto durante 20 minutos para
   que se cocine el arroz y se mezclen los sabores.
5. Pica el huevo cocido, añádelo y mezcla bien. 
6. Sirve el arroz con garbanzos en una legumbrera, corta la morcilla
   en 6 trozos y sírvela encima. Espolvorea con perejil picado.
** Garbanzos salteados con chorizo y pimentón
*** Información
- Comensales: 4 personas
- Fuente: http://www.directoalpaladar.com/recetas-de-legumbres-y-verduras/garbanzos-salteados-con-chorizo-y-pimenton-de-inspiracion-marroqui-receta
*** Ingredientes
- 400 gramos de garbanzos cocidos
- 1 cebolla roja
- 2 dientes de ajo
- 175 o 200 gramos de buen chorizo dulce o picante
- 2 hojas de laurel
- 2 cucharaditas de pimentón dulce
- 1 cucharadita de tomillo seco
- 1 cucharadita de salvia seca
- Zumo de limón
- Sal
- Pimienta negra
- Aceite de oliva virgen extra
*** Preparación
1. Enjuagar y escurrir bien los garbanzos cocidos al dente, o escurrir un bote
   de legumbre ya cocida. Retirar las posibles pieles que se hayan desprendido,
   o pelarlos si se desea. Reservar.
2. Picar la cebolla roja en trozos no muy pequeños, picar los dientes de ajo y
   trocear el chorizo, retirando la piel.
3. Calentar un par de cucharadas de aceite de oliva en una buena sartén o
   cazuela y cocinar la cebolla y el ajo unos 5 minutos, hasta que se
   transparenten. Añadir el chorizo y el laurel y saltear durante unos minutos.
4. Incorporar los garbanzos, el pimentón, el tomillo y la salvia, removiendo
   bien. Bajar el fuego, tapar y cocinar unos 15 o 20 minutos, para que se
   integren bien todos los sabores. Al final de la cocción, sazonar con zumo de
   limón al gusto, salpimentar y añadir un poco más de pimentón, si se desea.
** Olla gitana
*** Información
- Fuente: Escuela MasterChef
*** Ingredientes
- 200 gramos de garbanzos
- 200 gramos de patatas
- 1 cebolla
- 100 gramos de judias verdes
- 200 gramos de calabaza
- 2 peras
- 2 ajos
- Pimentón
- Aceite
- Clavo
- Azafrán
- Sal
- Hierbabuena
*** Preparación
1. Ponemos a cocer en una olla con agua los garbanzos (que han estado
   previamente en remojo). Colocamos un clavo y dos ajos junto a los
   garbanzos y tapamos, dejando cocer a fuego lento unos 40 o 50
   minutos.
2. Mientras, preparamos en una sartén con aceite un sofrito
   básico. Primero doramos el ajo laminado, agregamos la cebolla en
   brunoise, y posteriormente el tomate, dejando que se haga todo a
   fuego lento unos 50 minutos.
3. Añadimos a la olla la patata cacheada, la calabaza cortada en dados
   y la judía verde previamente cortada. Añadimos agua al guiso si es
   necesario. Tapamos y dejamos cocer a fuego lento hasta que estén
   tiernos todos los elementos. 
4. Rehogamos el sofrito y le añadimos pimentón justo antes de
   incorporarlo a la olla.
5. A continuación, echamos azafrán al guiso y, por último unos trozos
   de pera que se cocerán unos dos minutos con la olla tapada.
6. La olla gitana ya está lista para emplatar, con hierbabuena, menta
   o ingredientes al gusto.
** Potaje de vigilia
*** Información
- Fuente: Escuela MasterChef
*** Ingredientes para el potaje
- 300 gramos de garbanzos
- 150 gramos de espinacas baby
- 120 gramos de lomos de bacalao 
- 40 gramos de bacalao desmigado 
- 1 cebolla 
- 1 clavo
- 2 dientes de ajo
- Azafrán
*** Ingredientes para el majao
- 1 rebanada de pan frito
- 30 gramos de almendras tostadas
- 1 huevo cocido
- 1 diente de ajo
- Sal
*** Preparación
1. Remojamos previamente los garbanzos. Cuando estén hidratados los
   ponemos a cocer en una olla con agua y una pizca de sal.
2. Añadimos una cabeza de ajos, una cebolla claveteada y laurel a los
   garbanzos. Tapamos y lo dejamos a fuego lento durante unos 50 o 55
   minutos. 
3. Mientras, hacemos el “majao” triturando en un mortero el diente de
   ajo, el pan frito, las almendras tostadas, el huevo cocido y una
   pizca de sal.
4. Pasados los 55 minutos de cocción de los garbanzos sacamos un poco
   de caldo y lo vertemos en el “majao”, añadiéndole también unas
   hebras de azafrán. Removemos el majao y lo incorporamos a los
   garbanzos, para darle consistencia.
5. Adicionamos al guiso las migas de bacalao y las espinacas baby.
6. Colocamos los lomos de bacalao la superficie del guiso. Apagamos el
   fuego y dejamos que se atempere unos 6 minutos mientras los lomos
   alcanzan una temperatura aproximada de 45º o 50º.

#+LATEX: \clearpage
** Rancho canario
*** Información
- Comensales: 8 personas
- Fuente: http://www.hogarutil.com/cocina/recetas/legumbres/201401/rancho-canario-23423.html
*** Ingredientes
- 250 gramos de garbanzos
- 1 muslo de pollo
- 1/4 kilo de zancarrón de ternera
- 100 gramos de chorizo fresco
- 100 gramos de pasta del nº 4
- 2 patatas
- 1 cebolleta
- 1 tomate
- 5 dientes de ajo
- Agua
- Aceite de oliva virgen extra
- Sal
- 1 cucharadita de pimentón dulce
- 1 cucharadita de orégano
- Unas hebras de azafrán
- Perejil
*** Preparación
1. Pon las carnes (pollo, ternera y chorizo) en la olla, cubre con agua, sazona
   y ponla a calentar. Cuando empiece a hervir, retira la espuma y añade los
   garbanzos (remojados de víspera). Tapa y cuece todo durante 30 o 35 minutos
   (a partir de que empiece a salir el vapor).
2. Pela y pica los ajos y la cebolleta y ponlos a pochar. Cuando cojan un poco
   de color, agrega el tomate (pelado y picado) y rehógalo un poco. Sazona.
   Añade el pimentón, el orégano y unas hebras de azafrán. Mezcla bien.
3. Retira las carnes de la olla, pícalas y resérvalas. Agrega las verduras a la
   olla y mezcla bien. Pela las patatas, trocéalas e incorpóralas a la olla
   junto con los fideos. Tapa y cuece todo durante 5 a 7 minutos
   aproximadamente. Abre la olla e introduce las carnes picadas, mezcla bien y
   espolvorea con perejil picado. 
** Verduras guisadas con alubias y pasta
*** Información
- Comensales: 2 o 3 personas
- Fuente: http://www.directoalpaladar.com/recetas-de-legumbres-y-verduras/verduras-guisadas-con-alubias-y-pasta-receta
*** Ingredientes
- 80 gramos de alubias pintas
- 1 cebolla
- 2 dientes de ajo
- 1 zanahoria grande
- 100 gramos de judías verdes redondas
- 1 nabo
- 1 calabacín mediano
- 1 rama de apio
- 1 tomate grande maduro
- 60 gramos de pasta corta
- 2 cucharadas de mezcla de hierbas al gusto (romero, tomillo, perejil, salvia, laurel…)
- Saldo de verduras o agua
- Queso parmesano recién rallado
- Aceite de oliva
- Pimienta negra
- Sal
*** Preparación
1. Poner a remojo las alubias la noche antes si son muy duras o a primera hora
   de la mañana. Empezar a cocerlas con agua limpia unos 30 minutos antes de
    elaborar el resto del guiso. Lavar todas las verduras. Picar la cebolla y el
   ajo en piezas finas, y trocear el resto.
2. Calentar unas cucharadas de aceite de oliva en una olla o cazuela amplia y
   pochar la cebolla con el ajo y una pizca de sal. Añadir la zanahoria y el
   nabo y dar unas vueltas hasta que cojan color. Incorporar las judías verdes,
   el calabacín y el apio, y sazonar con una parte de las hierbas.
3. Cuando las verduras empiecen a estar tiernas, agregar las alubias y parte de
   su agua de cocción. Añadir caldo o agua hasta cubrir unos 3 dedos y llevar a
   ebullición. Dejar cocer a fuego lento unos 20 minutos y añadir el tomate
   rallado o bien picado.
4. Continuar la cocción unos 20 o 30 minutos más, vigilando el nivel de líquido.
   Añadir la pasta, el resto de hierbas aromáticas y salpimentar. Cocer hasta
   que la pasta esté lista, añadir queso rallado al gusto y tapar. Dejar reposar
   con el fuego apagado unos 5 o 10 minutos.
* Recetas básicas
** Sofrito
*** Ingredientes
- 1 decilitro de aceite de oliva
- 7 dientes de ajo
- 600 gramos de cebolla
- 600 gramos de tomate
- Sal
*** Preparación
1. Picamos ajo y lo añadimos a una sartén con aceite previamente
   calentado.
2. Después le incorporamos cebolla picada y doramos. Salamos y tapamos
   la cazuela, dejándola a fuego lento.
3. Escaldamos el tomate durante unos 8 segundos, lo ponemos en agua
   fría y lo pelamos antes de cortarlo y retirarle las semillas.
4. Añadimos el tomate al sofrito, lo tapamos y dejamos una cocción de
   90 minutos.
** Tomate frito casero
*** Información
- Fuente: http://webosfritos.es/2011/10/tomate-frito-casero/
*** Ingredientes
- 2 kilos de tomate pera natural
- 2 cucharadas soperas de azúcar
- 1 cucharadita de las de café no muy llena de sal
- 4 cucharadas soperas de aceite de oliva virgen extra
*** Preparación
1. Poner agua a hervir en un cazo. Hacer un corte superficial en
   forma de cruz en el culo de los tomates y pasarlos 20 segundos por
   el agua hirviendo. Refrescarlos en un bol con agua fría y pelarlos.
2. Trocearlos y triturarlos con la batidora, pero no mucho: si quedan
   pequeños trocitos le darán una textura interesante.
3. Poner una sartén con el aceite de oliva virgen extra y cuando esté
   caliente, retirarlo del fuego. Cuando pierda un poco de
   temperatura, echar el tomate, la sal y la mitad del azúcar, y
   ponerle una tapa que tenga orificios de salida de vapor —es
   necesaria para que al principio no salte el tomate—. Volver a
   ponerlo a fuego medio y remover cada 10 minutos con una cuchara de
   madera.
4. Cuando pasen 25 minutos y vaya espesando poco a poco, podremos
   quitar la tapa. Añadir el resto del azúcar. Aproximadamente el
   tomate estará hecho en 45 o 50 minutos —depende de los tomates—.
5. Probar y rectificar de sal o azúcar si hace falta y tenerlo un par
   de minutos más.
*** Consejos
- ¿Cuánto jugo tiene que llevar el tomate para ponerlo a freír?
  + Si es tomate pera, el que suelta el propio tomate.
  + Si es de otras variedades, coger un vaso del jugo que desprende al
    trocearlo en el cuenco en el que lo vamos a triturar y
    retirarlo. Normalmente el caldo que va soltando cubre casi las
    tres cuartas partes del tomate, cuando se trata de variedades de
    tomate muy jugoso; al triturarlo soltará aún más, tardará
    demasiado en hacerse y no quedará espeso.
  + Si es comprado envasado entero y pelado, desechar el jugo:
    solamente con el que sueltan al triturarlos es suficiente.
  + Si es comprado envasado triturado para freír, como ya viene
    triturado, es lo que hay, y lo suelen tener bien proporcionado. A
    veces varía tanto el espesor en las marcas que pienso si alguno
    llevará espesante para que se haga antes en casa y nos quedemos
    tan contentos.
- Se puede congelar perfectamente. Preferiblemente descongelarlo en
  el frigorífico.
- Al principio hay que ponerlo a fuego medio-alto, por ejemplo, en una
  vitrocerámica, en el 7, pero luego, conforme va evaporando líquido
  hay que bajarlo al 3 o 4 porque es muy fácil que el tomate se queme
  un poco al final, cuando esté ya hecho.
