** Cómo desmoldar una tarta
1. Engrasar la base y las paredes del molde.
2. Cortar dos tiras anchas de papel de hornear y ponerlas sobre la base del
   molde en forma de cruz, de tal manera que sobresalgan por los bordes.
3. Poner otro poco de mantequilla por encima de las tiras del papel.
4. Colocar con delicadeza la masa quebrada o el hojaldre en el molde y proceder
   como te indique la receta.
5. Una vez horneada la tarta, y en cuanto enfríe un poco para poderla manipular,
   tirar hacia arriba de las tiras de papel de hornear y depositarla con
   cuidado sobre una rejilla.
** Crema pastelera
*** Ingredientes
- 250 mililitros leche
- 2 huevos medianos enteros medianos
- 60 gramos de azúcar 
- 20 gramos de Maicena
- 1 vaina de vainilla
*** Preparación tradicional
1. Poner en un vaso de la batidora todos los ingredientes menos la
   vainilla. Batirlos bien con la batidora de varillas.
2. Abrir la vaina de vainilla por la mitad y raspar con la punta del
   cuchillo el interior de la misma. Echarlo al bol y mezclar.
3. Echar el contenido del mismo en un cazo y poner a fuego medio sin
   dejar de remover con unas varillas hasta que espese. Como mucho
   tarda un par de minutos.
4. Quitar del fuego y pasarla a un cuenco. En cuanto esté templada,
   poner un plástico tocando la superficie de la crema para que no
   cree costra. Meter en el frigorífico hasta su uso.

** Tarta arcoiris
- http://www.trusper.com/tips/MELTED-RAINBOW-CAKE-/15000717
** Volovanes de hojaldre
*** Información
- Fuente: http://javirecetas.hola.com/volovanes-recetas-paso-a-paso/
*** Ingredientes
- 1 lamina de hojaldre
- 1 huevo
- Unos 100 gramos de garbanzos para prensar la masa
- 2 cortapastas de distinto diámetro
*** Preparación
1. Extiende la masa de hojaldre y corta 12 círculos con el cortapastas grande.
   Retira la masa sobrante y con el cortapastas pequeño corta en el centro de 8
   de los 12 círculos (fíjate en la fotografía). Te quedarán 4 círculos y 8
   anillos. Los círculos pequeños que sobran puedes hornearlos y usarlos como
   aperitivo de hojaldre con algún relleno.
2. Pinta con huevo batido la periferia (el borde) de los 4 círculos que hemos
   dejado sin cortar y ponemos sobre él un anillo de masa. Pintamos sobre el
   anillo recién puesto y colocamos el segundo anillo. Si queremos podemos
   volver a pintar con huevo este segundo anillo para que los volovanes cojan
   un color dorado en el horno.
3. Pinchamos la base de los volovanes para que no crezcan (pero no toques los
   anillos) y colocamos unos garbanzos (o cualquier otra legumbre) en el centro
   para asegurarnos de que no crecerá el hojaldre por el centro.
4. Introducimos en el horno precalentado a 200 grados y los dejamos 15 minutos.
   Después dejamos enfriar, quitamos los garbanzos y listo.
